# config.yml

# 当前测试端设备的唯一名称
device_name: "my-first-client"

# 全局 GitHub 前置代理前缀
proxy_prefix: "${GITHUB_PROXY}"

# Gist 配置
gist:
  token: "${GITHUB_TOKEN}"
  gist_id: "aaaabbbbcccc111122223333"

# CloudflareSpeedTest 配置
cf:
  binary: "/usr/local/bin/CloudflareSpeedTest"
  # [修改] 移除 -raw, -json 等不适用参数, 核心是 -o
  # -o 参数由程序自动添加，无需在此配置
  args:
    - "-dn"
    - "20" # 下载测速数量
    - "-t"
    - "4"  # 延迟测速次数
  # [修改] 输出文件名更改为 .csv
  output_file: "result.csv"

  # 自动更新配置
  update:
    check: true
    api_url: "https://api.github.com/repos/XIU2/CloudflareSpeedTest/releases/latest"