# config.yml

# Cron 表达式，用于定时执行测速任务
cron: "0 0 * * *"

# 当前测试端设备的唯一名称
device_name: "my-first-client"

# 当前设备所属的线路运营商 (ct, cu, cm)
line_operator: "cu"

# 是否启用 IPv6 测试 (true / false)
test_ipv6: true

# 全局 GitHub 前置代理前缀
proxy_prefix: "${GITHUB_PROXY}"

# Gist 配置
gist:
  token: "${GITHUB_TOKEN}"
  gist_id: "aaaabbbbcccc111122223333"

# 测速任务配置
test_options:
  # 即时重试：结果数量下限，低于此值则触发重试
  min_results: 5
  # 即时重试：最大重试次数
  max_retries: 3
  # 即时重试：重试间隔时间（单位：秒）
  retry_delay: 5

  # [新功能] 延迟重试：当以上即时重试全部失败后，启用此机制
  delayed_retry:
    enabled: true       # 是否启用
    delay_minutes: 30   # 失败后多少分钟后再次尝试

  # 上传到 Gist 的最大 IP 数量
  gist_upload_limit: 10

# CloudflareSpeedTest 配置
cf:
  binary: "/usr/local/bin/CloudflareSpeedTest"
  args:
    - "-dn"
    - "20"
    - "-t"
    - "4"
  output_file: "result.csv"

# IPv6 测试配置
cf6:
  binary: "/usr/local/bin/CloudflareSpeedTest"
  args:
    - "-dn"
    - "10"
    - "-sl"
    - "20"
  output_file: "result6.csv"

# 自动更新配置
update:
  check: true
  api_url: "https://api.github.com/repos/XIU2/CloudflareSpeedTest/releases/latest"

# 通知配置
notifications:
  enabled: true
  pushplus:
    token: ""
  telegram:
    bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: "${TELEGRAM_CHAT_ID}"
    proxy:
      enabled: false
      type: "socks5"
      address: "127.0.0.1:1080"
      api_url: ""