# config.yml

# 当前测试端设备的唯一名称
device_name: "my-first-client"

# [核心] 当前设备所属的线路运营商 (ct, cu, cm)
# 这个值将被用于生成上传到 Gist 的文件名
line_operator: "cu" # 例如 "cu" 代表联通

# [核心] 是否启用 IPv6 测试 (true / false)
test_ipv6: true

# 全局 GitHub 前置代理前缀
proxy_prefix: "${GITHUB_PROXY}"

# Gist 配置
gist:
  token: "${GITHUB_TOKEN}"
  gist_id: "aaaabbbbcccc111122223333"

# [新增] 测速任务配置
test_options:
  # 结果数量下限，低于此值则触发重试
  min_results: 5
  # 最大重试次数
  max_retries: 3
  # 上传到 Gist 的最大 IP 数量
  gist_upload_limit: 10

# CloudflareSpeedTest 配置
cf:
  binary: "/usr/local/bin/CloudflareSpeedTest"
  # [修改] 移除 -raw, -json 等不适用参数, 核心是 -o
  # -o 参数由程序自动添加，无需在此配置
  args:
    - "-dn"
    - "20" # 下载测速数量
    - "-t"
    - "4"  # 延迟测速次数
  # [修改] 输出文件名更改为 .csv
  output_file: "result.csv"

# [核心] IPv6 测试配置 (仅在 test_ipv6: true 时启用)
cf6:
  binary: "/usr/local/bin/CloudflareSpeedTest"
  args:
    - "-dn"
    - "10" # IPv6 可以测试少一些
    - "-sl"
    - "20"
  # IPv6 本地输出的 CSV 文件名
  output_file: "result6.csv"

  # 自动更新配置
update:
  check: true
  api_url: "https://api.github.com/repos/XIU2/CloudflareSpeedTest/releases/latest"

# [新增] 通知配置
notifications:
  enabled: true
  pushplus:
    token: "your_pushplus_token"
  telegram:
    bot_token: "your_bot_token"
    chat_id: "your_chat_id"